site_name: cloud-monitor
site_url: https://cloud-monitor.github.io/monitors
site_description: monitor stub, not only cloud 
site_author: Hoa Ngo

repo_url: https://github.com/cloud-monitor/auto_scaling_auto_healing
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
nav:
    - Index: index.md
    - INTRODUCTION:
        - Issue describe: issue/readme.md
    - TECHNOLOGY DETAIL:
        - vitrage: tech_detail/vitrage/vitrage-doc/architecture.md
        - mistral: tech_detail/mistral/mistral-doc/readme.md
        - zabbix: tech_detail/zabbix/zabbix-doc/readme.md
        - TICK : tech_detail/tick/tick-doc/readme.md
    - SCENARIO:
        - usecase-1: usecase/usecase1.md
    - BLUEPRINT:
        - Propose: issue/propose/readme.md
        - Start: issue/start/readme.md
        - In process: issue/in_process/readme.md
        - Need review: issue/need_review/readme.md
        - Sloved: issue/sloved/readme.md
    - ABOUT:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - admonition
